-- Effective Propositional Inference
-- Informatics 2D
-- Assignment 1
-- 2010-2011
--
-- Parser for SAT examples
-- DO NOT EDIT THIS FILE --


module SatParser where

import System.Environment
import Monad
import Text.ParserCombinators.Parsec
import IO
import Char
import List
import Assignment

getExample file = do
                    satfile <- openFile file ReadMode
                    formula <- doRead satfile []
                    hClose satfile
                    return formula
 
doRead satfile clauses = do 
                          fileopen <- hIsEOF satfile
                          case fileopen of
                             True -> return clauses
                             False -> do 
                                        line <- hGetLine satfile
                                        doRead satfile ((readClause line):clauses)

readClause line = case (parse parseClause "" line) of
    Left err -> return []
    Right clause -> return clause 
                   

parseLiteral :: Parser Literal
parseLiteral = do{ 
                 x <- many1 (char '-' <|> digit);
                 many (char ' ');
                 if (not (isNumber x)) 
                  then fail ""
                  else if ((x!!0) == '-') 
                    then return (False,tail x)
                    else return (True,x)
                      
                 }

isNumber ('-':[]) = False
isNumber ('-':xs) = and (map (\x -> (isDigit x)) xs)
isNumber (x:xs) = if (isDigit x)
                       then and (map (\x -> (isDigit x)) xs)
                       else False

parseClause :: Parser Clause
parseClause = do {many (char ' ');
                  literals <- many1 parseLiteral; 
                  many (char ' ');
                  return (filter (\x -> x /= (True,"0")) literals)
                 }

