-- Effective Propositional Inference
-- Informatics 2D
-- Assignment 1
-- 2010-2011
--
-- Main function for WalkSat
-- DO NOT EDIT THIS FILE --

module Main where

import System.Environment
import Assignment
import SatParser

main = do
        args <- getArgs
        sat <- getExample (args!!0)
        case (map (\x -> (x!!0)) (filter (\x -> x /= [[]]) sat)) of
         [] -> putStrLn "Not a valid Sat problem"
         formula -> test formula (read (args!!1)::Float) (read (args!!2)::Int)


test formula prob maxflips = do
                 putStrLn "Using WalkSat ..." 
                 walksat <- walkSat formula prob maxflips
  		 case walksat of
  		   Nothing -> putStrLn("WalkSat: Returned failure!")
		   Just (m,f) -> putStrLn ("WalkSat: Found model for formula in " ++ (show (maxflips - f)) ++ " flips.")


